5.4
Getting error
Assets\Scripts\DifficultyButton.cs(29,21): error CS1061: 'GameManager' does not contain a definition for 'StartGame' and no accessible extension method 'StartGame' accepting a first argument of type 'GameManager' could be found (are you missing a using directive or an assembly reference?)